// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HalvorsonCredit.Models
{
    public partial class UserInstitution
    {
        public int UserId { get; set; }
        public int InstitutionId { get; set; }

        public virtual Institution Institution { get; set; }
        public virtual User User { get; set; }
    }
}